pipeline {
    agent {
        docker {
            image 'node:lts-alpine'
            args '-p 3000:3000 -p 5000:5000'
        }
    }
    environment {
        CI = 'true'
        HOME = '/tmp
    }
    stages {
        stage('Clean workspace') {
            steps {
                sh '''
                    rm -rf node_modules
                    rm -rf package-lock.json
                    rm -rf /tmp/.npm
                '''
            }
        }
        stage('Build') {
            steps {
                sh '''
                    npm cache clean --force
                    npm install --legacy-peer-deps --loglevel verbose
                '''
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver for development') {
            when {
                branch 'feature'
            }
            steps {
                sh './jenkins/scripts/deliver-for-development.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
        stage('Deploy for productions') {
            when {
                branch 'master'
            }
            steps {
                sh './jenkins/scripts/deploy-for-production.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
