pipeline {
    agent {
        docker {
            image 'node:lts-alpine'
            args '-u root -v $WORKSPACE:/usr/src/app -w /usr/src/app' // Run as root to avoid permission issues
        }
    }

    environment {
        CI = 'true'
        HOME = '/tmp'
    }

    options {
        skipDefaultCheckout(true)
    }

    stages {
        stage('Clean workspacesssss') {
            steps {
                cleanWs()
                sh 'rm -rf /tmp/.npm'
            }
        }

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install dependencies') {
            steps {
                sh '''
                    npm cache clean --force
                    rm -rf node_modules package-lock.json
                    npm install --legacy-peer-deps --loglevel verbose
                '''
            }
        }

        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }

        stage('Deliver for development') {
            when {
                branch pattern: "feature/.*", comparator: "REGEXP"
            }
            steps {
                sh './jenkins/scripts/deliver-for-development.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }

        stage('Deploy for production') {
            when {
                branch 'master'
            }
            steps {
                sh './jenkins/scripts/deploy-for-production.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
